config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :commands

  # Configure API routes to get the mod's zip file.
  # Either the last uploaded or the last updated mod?
  namespace :api do
    namespace :v1 do
      get 'download_latest_mod', to: 'dashboard#download_latest_mod'
      get 'check_current_version', to: 'dashboard#check_current_version'
      # Test endpoint now takes a mod id as a parameter
      get 'tests', to: 'dashboard#test_latest', as: :test_latest
      get 'test/mod/:id', to: 'dashboard#test_mod', as: :test_mod
      get 'command_test', to: 'dashboard#command_test'
    end
  end

  resources :mods
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/mod.rb
class Mod < ApplicationRecord
  has_one_attached :zip, dependent: :destroy
  has_rich_text :description
  after_update :rename_zip_if_needed

  private

  def rename_zip_if_needed
    original_filename = zip.blob.filename.to_s if zip.attached?
    if saved_change_to_attribute?(:desired_attribute)
        RenameActiveStorageAttachmentJob.perform_later(self, 'avatar', "original_filename")
    end
  end
end

app/controllers/mods_controller.rb
class ModsController < ApplicationController
  before_action :set_mod, only: %i[ show edit update destroy ]

  # GET /mods or /mods.json
  def index
    @mods = Mod.all
  end

  # GET /mods/1 or /mods/1.json
  def show
  end

  # GET /mods/new
  def new
    @mod = Mod.new
  end

  # GET /mods/1/edit
  def edit
  end

  # POST /mods or /mods.json
  def create
    @mod = Mod.new(mod_params)

    respond_to do |format|
      if @mod.save
        format.html { redirect_to mod_url(@mod), notice: "Mod was successfully created." }
        format.json { render :show, status: :created, location: @mod }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mods/1 or /mods/1.json
  def update
    respond_to do |format|
      if @mod.update(mod_params)
        format.html { redirect_to mod_url(@mod), notice: "Mod was successfully updated." }
        format.json { render :show, status: :ok, location: @mod }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mods/1 or /mods/1.json
  def destroy
    @mod.destroy!

    respond_to do |format|
      format.html { redirect_to mods_url, notice: "Mod was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mod
      @mod = Mod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mod_params
      params.require(:mod).permit(:name, :zip, :description)
    end
end

app/helpers/mods_helper.rb
module ModsHelper
end

app/views/mods/_form.html.erb
<%= form_with(model: mod) do |f| %>
  <label class="block">
    <span class="block text-sm font-medium text-slate-700">Username</span>
    <%= f.text_field :name, placeholder: "Modpack Name...", class: "mt-1 block w-full px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400
      focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500" %>
    <!-- Using form state modifiers, the classes can be identical for every input -->
  </label>
  <label class="block">
    <span class="block text-sm font-medium text-slate-700">Description</span>
    <%= f.rich_text_area :description, placeholder: "About the modpack..." %>
    <!-- Using form state modifiers, the classes can be identical for every input -->
  </label>
  <div>
    <%= f.label "Zip File" %>
    <%= f.file_field :zip %>
  </div>
  <div class="mt-2">
    <%= f.submit "Update", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  </div>
<% end %>

app/views/mods/_mod.html.erb
<div id="<%= dom_id mod %>" class="max-w-sm rounded overflow-hidden shadow-lg">
  <img class="w-full" src="/img/card-top.jpg" alt="Sunset in the mountains">
  <div class="px-6 py-4">
    <div class="font-bold text-xl mb-2"><%= mod.name %></div>
    <p class="text-gray-700 text-base">
      <%= mod.description %>
    </p>
  </div>
  <div class="px-6 pt-4 pb-2">
    <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"><%= link_to mod.zip.filename, url_for(mod.zip), class: "text-blue-500" if mod.zip.attached? %>
    </span>
    <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
      <%= link_to "View Modpack", mod, class: "text-blue-500" %>
    </span>
    <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
      <%= link_to "Deploy", api_v1_test_mod_path(mod), class: "text-blue-500" %>
    </span>
  </div>
</div>

app/views/mods/edit.html.erb
<h1>Editing mod</h1>

<%= render "form", mod: @mod %>

<br>

<div>
  <%= link_to "Show this mod", @mod %> |
  <%= link_to "Back to mods", mods_path %>
</div>

app/views/mods/index.html.erb
<p style="color: green"><%= notice %></p>
<h1 class="text-3xl font-bold">Mods</h1>
<div id="mods" class="grid grid-cols-3 gap-4">
  <% @mods.each do |mod| %>
    <div class="col-start-1"></div>
    <div class="container">
      <%= render mod %>
    </div>
    <div class="col-start-1"></div>
  <% end %>
</div>
<%= link_to "New mod", new_mod_path %>

app/views/mods/new.html.erb
<h1>New mod</h1>

<%= render "form", mod: @mod %>

<br>

<div>
  <%= link_to "Back to mods", mods_path %>
</div>

app/views/mods/show.html.erb
<p style="color: green"><%= notice %></p>
<h1 class="text-3xl font-bold"><%= link_to "Mods", mods_path %></h1>
<div id="mods" class="grid grid-cols-3 gap-4 mt-10">
  <div class="col-start-1"></div>
  <%= render @mod %>
  <div class="col-start-1"></div>
  <div>
    <%= link_to "Edit this mod", edit_mod_path(@mod) %> |
    <%= link_to "Back to mods", mods_path %>
    <%= button_to "Destroy this mod", @mod, method: :delete %>
  </div>
</div>