config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :commands

  # Configure API routes to get the mod's zip file.
  # Either the last uploaded or the last updated mod?
  namespace :api do
    namespace :v1 do
      get 'download_latest_mod', to: 'dashboard#download_latest_mod'
      get 'check_current_version', to: 'dashboard#check_current_version'
      # Test endpoint now takes a mod id as a parameter
      get 'tests', to: 'dashboard#test_latest', as: :test_latest
      get 'test/mod/:id', to: 'dashboard#test_mod', as: :test_mod
      get 'command_test', to: 'dashboard#command_test'
    end
  end

  resources :mods
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/command.rb
class Command < ApplicationRecord
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  before_action :set_command, only: %i[ show edit update destroy ]

  # GET /commands or /commands.json
  def index
    @commands = Command.all
  end

  # GET /commands/1 or /commands/1.json
  def show
  end

  # GET /commands/new
  def new
    @command = Command.new
  end

  # GET /commands/1/edit
  def edit
  end

  # POST /commands or /commands.json
  def create
    @command = Command.new(command_params)


    respond_to do |format|
      if @command.save
        RconClient.instance.execute(@command.body)
        format.html { redirect_to command_url(@command), notice: "Command was successfully created." }
        format.json { render :show, status: :created, location: @command }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commands/1 or /commands/1.json
  def update
    respond_to do |format|
      if @command.update(command_params)
        format.html { redirect_to command_url(@command), notice: "Command was successfully updated." }
        format.json { render :show, status: :ok, location: @command }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commands/1 or /commands/1.json
  def destroy
    @command.destroy!

    respond_to do |format|
      format.html { redirect_to commands_url, notice: "Command was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_command
      @command = Command.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def command_params
      params.require(:command).permit(:body)
    end

    def create_command_execute_file(command_to_run, file_name)
      # Create the flag file
      if Rails.env.development?
        data_directory = Rails.root.join('data')
        File.write("#{data_directory}/#{file_name}", command_to_run, mode: 'a')
      else
        File.write("/data/#{file_name}", command_to_run, mode: 'a')
      end
    end
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/views/commands/_command.html.erb
<div id="<%= dom_id command %>">
  <p>
    <strong>Body:</strong>
    <%= command.body %>
  </p>

</div>

app/views/commands/_form.html.erb
<%= form_with(model: command) do |form| %>
  <% if command.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(command.errors.count, "error") %> prohibited this command from being saved:</h2>

      <ul>
        <% command.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/commands/edit.html.erb
<h1>Editing command</h1>

<%= render "form", command: @command %>

<br>

<div>
  <%= link_to "Show this command", @command %> |
  <%= link_to "Back to commands", commands_path %>
</div>

app/views/commands/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Commands</h1>

<div id="commands">
  <% @commands.each do |command| %>
    <%= render command %>
    <p>
      <%= link_to "Show this command", command %>
    </p>
  <% end %>
</div>

<%= link_to "New command", new_command_path %>

app/views/commands/new.html.erb
<h1>New command</h1>

<%= render "form", command: @command %>

<br>

<div>
  <%= link_to "Back to commands", commands_path %>
</div>

app/views/commands/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @command %>

<div>
  <%= link_to "Edit this command", edit_command_path(@command) %> |
  <%= link_to "Back to commands", commands_path %>

  <%= button_to "Destroy this command", @command, method: :delete %>
</div>